export default {
  auth: 'auth',
  scheduledMeeting: 'scheduledMeeting',
  user: 'user',
  invite: 'invite',
  controlMeeting: 'controlMeeting',
  group: 'group',
  userGroup: 'userGroup',
  privateRoom: 'privateRoom',
  passProtection: 'passProtection',
  DescriptivePoll: 'DescriptivePoll',
  OptionalpPoll: 'OptionalpPoll',
  PollingDecRecived: 'PollingDescRecived',
  PollingOptiRecived: 'PollingOptiRecived',
  polling: 'polling',
  OptionalResult: 'OptionalResult',
  DescriptiveResult: 'DescriptiveResult',
  proceedings: 'proceedings',
  room:'room',
  billing:'billing',
  report:'report',
  log:'log',
  ldap:'ldap',
  meetingAttribute:'meetingAttribute',
  setting:'setting',
  agenda:'agenda',
  customer:'customer',
}
